// auto-generated by superconfig - DO NOT EDIT MANUALLY
export {};

declare module 'superconfig' {
  export interface SuperConfig {
    NAME: string;
    GIRLFRIEND: string;
    GOD: string;
    DOG: string;
    POKEMON: string;
  }
}
